-- BEGIN;
CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(320) NOT NULL,
  pass CHAR(60) NOT NULL);

CREATE TABLE IF NOT EXISTS recettes (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  label TEXT NOT NULL,
  amount INTEGER NOT NULL,
  createdAt DATE NOT NULL,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE IF NOT EXISTS depenses (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  label TEXT NOT NULL,
  amount INTEGER NOT NULL,
  createdAt DATE NOT NULL,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE TABLE IF NOT EXISTS comptes (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  courant INTEGER,
  epargne INTEGER,
  atTime DATE NOT NULL,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE);


-- Create table
-- COMMIT;