-- BEGIN;

CREATE TABLE IF NOT EXISTS recettes (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  label TEXT NOT NULL,
  amount INTEGER NOT NULL,
  createdAt DATE NOT NULL,
  user TEXT NOT NULL);


CREATE TABLE IF NOT EXISTS depenses (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  label TEXT NOT NULL,
  amount INTEGER NOT NULL,
  createdAt DATE NOT NULL,
  user TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS comptes (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  courant INTEGER,
  epargne INTEGER,
  atTime DATE NOT NULL,
  user TEXT NOT NULL);

-- Create table
-- COMMIT;